set(USE_SDL2 OFF)
set(FILE_SYSTEM \"/dev/mmcblk0p4\")
set(PATH_DEFAULT \"/mnt\")
set(PATH_DEFAULT_RIGHT \"/mnt/FunKey\")
set(SCREEN_WIDTH 240)

set(CMDR_KEY_UP SDLK_u) # Up
set(CMDR_KEY_RIGHT SDLK_r) # Right
set(CMDR_KEY_DOWN SDLK_d) # Down
set(CMDR_KEY_LEFT SDLK_l) # Left

set(CMDR_KEY_SYSTEM SDLK_y) # Y
set(CMDR_KEY_PAGEUP SDLK_m) # L
set(CMDR_KEY_PAGEDOWN SDLK_n) # R
set(CMDR_KEY_OPEN SDLK_a) # A
set(CMDR_KEY_PARENT SDLK_b) # B
set(CMDR_KEY_OPERATION SDLK_x) # X
set(CMDR_KEY_SELECT SDLK_k) # SELECT
set(CMDR_KEY_TRANSFER SDLK_s) # START
set(CMDR_KEY_MENU SDLK_q) # MENU
